

fluidPage(column(width = 12,
                 tabBox(title = "", width = NULL,
                        tabPanel(title = tagList(icon("dna"), "batch1"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     textAreaInput(inputId = "NZM_geneheatmap_genelist_b1", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_dist_b1", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_hclust_b1", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_color_b1", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     do.call(actionBttn, c(list( inputId = "NZM_make_geneheatmap_b1", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     #This was done to test what kind of output textAreaInput gives
                                                     #textOutput("NZM_geneheatmap_genelist_b1_out"),
                                                     plotly::plotlyOutput("NZM_hclust_heatmap_b1_out", height = "600px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batch2"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     textAreaInput(inputId = "NZM_geneheatmap_genelist_b2", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_dist_b2", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_hclust_b2", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_color_b2", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     do.call(actionBttn, c(list( inputId = "NZM_make_geneheatmap_b2", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("NZM_hclust_heatmap_b2_out", height = "800px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batch1and2"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     textAreaInput(inputId = "NZM_geneheatmap_genelist_b1and2", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_dist_b1and2", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_hclust_b1and2", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "NZM_geneheatmap_color_b1and2", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     do.call(actionBttn, c(list( inputId = "NZM_make_geneheatmap_b1and2", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("NZM_hclust_heatmap_b1and2_out", height = "800px") %>% withSpinner(),
                                                 )
                                          )))
                 )
)
)
                        