

fluidPage(column(width = 12,
                 tabBox(title = "", width = NULL,
                        tabPanel(title = tagList(icon("dna"), "correlation plot"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the correlation plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make_boxplot to generate the new figure",
                                                     helpText("Type PDL1.protein as one of the genes to look at PD-L1 expression levels"),
                                                     textInput(inputId= "PDL1_corplot_gene1", label = "Enter your gene (x-axis):", value = "SOX10"), 
                                                     textInput(inputId = "PDL1_corplot_gene2", label = "Enter your gene (y-axis):", value = "MITF"),
                                                     selectInput(input = "PDL1_corplot_optional_gene3", label = "add a third gene or mutation status", choices  = c("none","third_gene", "mutation_status")),
                                                     conditionalPanel(condition = "input.PDL1_corplot_optional_gene3=='third_gene'",
                                                                      textInput(inputId= "PDL1_corplot_select_gene1", label = "Enter your gene", value = "CD274")),
                                                     conditionalPanel(condition = "input.PDL1_corplot_optional_gene3=='mutation_status'",
                                                                      radioButtons(inputId = "PDL1_corplot_mutgrp", 
                                                                                   label = "select mutation group", 
                                                                                   #"all samples" = "no.subtype",
                                                                                   choices = list("BRAF/NRAS/WT" = "mut.subtype"), 
                                                                                   selected = "mut.subtype")),
                                                                      #materialSwitch(inputId = "PDL1_corplot_mutgrp", 
                                                                                   #label = "BRAF/NRAS mutation group", 
                                                                                   #value = FALSE,
                                                                                   #status = "primary"),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_corplot", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                     downloadButton(outputId = "PDL1_download_corplot_data",label = "Download data"))),
                                          column(width = 9,
                                                 box(title = "correlation plot",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_plotly_corplot_out") %>% withSpinner(),
                                                     textOutput("PDL1_corvalues_out"), 
                                                     DT::DTOutput("DT_PDL1_corplot_df") %>% withSpinner()))
                                 )),
                        tabPanel(title = tagList(icon("dna"), "co-expression analysis"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "co-expression analysis"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     textInput(inputId= "PDL1_coexp_gene1", label = "Enter your gene", value = "PAX3"),
                                                     selectInput(inputId= "PDL1_coexp_method", label = "correlation coefficient", choices = c("pearson","spearman","kendall"), selected = "pearson"),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_coexp", label = "make table", icon = icon("play")), actionBttnParams)),
                                                     downloadButton(outputId = "PDL1_download_coexp_data",label = "Download data"))),
                                          column(width = 9,
                                                 box(title = "coexpression analysis",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     DT::DTOutput("DT_PDL1_coexp_df") %>% withSpinner()
                                                     ))
                                 )),
                        tabPanel(title = tagList(icon("dna"), "correlation plot (select samples)"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the correlation plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     textInput(inputId= "PDL1_corplot_select_gene1", label = "Enter your gene (x-axis):", value = ""), 
                                                     textInput(inputId = "PDL1_corplot_select_gene2", label = "Enter your gene (y-axis):", value = ""),
                                                     selectizeInput(inputId = "PDL1_sampleselect_g1_corplot","select samples",choices= PDL1_all_samples, multiple=TRUE),
                                                     selectInput(input = "PDL1_corplot_optional_select_gene3", label = "add a third gene or mutation status", choices  = c("none","third_gene", "mutation_status")),
                                                     conditionalPanel(condition = "input.PDL1_corplot_optional_select_gene3=='third_gene'",
                                                                      textInput(inputId= "PDL1_corplot_select_gene3", label = "Enter your gene", value = "CD274")),
                                                     conditionalPanel(condition = "input.PDL1_corplot_optional_select_gene3=='mutation_status'",
                                                                      radioButtons(inputId = "PDL1_corplot_select_mutgrp", 
                                                                                   label = "select mutation group", 
                                                                                   #"all samples" = "no.subtype",
                                                                                   choices = list("BRAF/NRAS/WT" = "mut.subtype"), 
                                                                                   selected = "mut.subtype")),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_corplot_samples", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                     downloadButton(outputId = "PDL1_download_corplot_data_samples", label = "Download data"))),
                                          column(width = 9,
                                                 box(title = "correlation plot with selected samples",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_plotly_corplot_samples_out") %>% withSpinner(),
                                                     textOutput("PDL1_corvalues_samples_out"),
                                                     DT::DTOutput("DT_PDL1_corplot_samples_df") %>% withSpinner()))
                                 ))
                                 
                 )
)
)