

fluidPage(column(width = 12,
                 tabBox(title = "", width = NULL,
                        tabPanel(title = tagList(icon("dna"), "batch1"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     checkboxInput("PDL1_geneheatmap_samples_b1","Select samples instead of showing all samples?", value=FALSE),
                                                     conditionalPanel("input.PDL1_geneheatmap_samples_b1==true",
                                                                      selectizeInput(inputId= "PDL1_geneheatmap_samplelist_b1", label = "select your samples:",choices = PDL1_batch1_samples, multiple = TRUE)),
                                                     textAreaInput(inputId = "PDL1_geneheatmap_genelist_b1", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_dist_b1", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_hclust_b1", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_color_b1", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     sliderInput(inputId = "PDL1_geneheatmap_colsize_b1", label = "sample name size", min = 0, max = 20, value = 10, step = 1),
                                                     sliderInput(inputId = "PDL1_geneheatmap_rowsize_b1", label = "gene name size", min = 0, max = 20, value = 10, step = 1),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_geneheatmap_b1", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     #This was done to test what kind of output textAreaInput gives
                                                     #textOutput("PDL1_geneheatmap_genelist_b1_out"),
                                                     plotly::plotlyOutput("PDL1_hclust_heatmap_b1_out", height = "600px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batch2"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     checkboxInput("PDL1_geneheatmap_samples_b2","Select samples instead of showing all samples?", value=FALSE),
                                                     conditionalPanel("input.PDL1_geneheatmap_samples_b2==true",
                                                                      selectizeInput(inputId= "PDL1_geneheatmap_samplelist_b2", label = "select your samples:",choices = PDL1_batch2_samples, multiple = TRUE)),
                                                     textAreaInput(inputId = "PDL1_geneheatmap_genelist_b2", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_dist_b2", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_hclust_b2", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_color_b2", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     sliderInput(inputId = "PDL1_geneheatmap_colsize_b2", label = "sample name size", min = 0, max = 20, value = 10, step = 1),
                                                     sliderInput(inputId = "PDL1_geneheatmap_rowsize_b2", label = "gene name size", min = 0, max = 20, value = 10, step = 1),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_geneheatmap_b2", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_hclust_heatmap_b2_out", height = "800px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batch3"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     checkboxInput("PDL1_geneheatmap_samples_b3","Select samples instead of showing all samples?", value=FALSE),
                                                     conditionalPanel("input.PDL1_geneheatmap_samples_b3==true",
                                                                      selectizeInput(inputId= "PDL1_geneheatmap_samplelist_b3", label = "select your samples:",choices = PDL1_batch3_samples, multiple = TRUE)),
                                                     textAreaInput(inputId = "PDL1_geneheatmap_genelist_b3", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_dist_b3", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_hclust_b3", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_color_b3", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     sliderInput(inputId = "PDL1_geneheatmap_colsize_b3", label = "sample name size", min = 0, max = 20, value = 10, step = 1),
                                                     sliderInput(inputId = "PDL1_geneheatmap_rowsize_b3", label = "gene name size", min = 0, max = 20, value = 10, step = 1),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_geneheatmap_b3", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_hclust_heatmap_b3_out", height = "800px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batch4"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     checkboxInput("PDL1_geneheatmap_samples_b4","Select samples instead of showing all samples?", value=FALSE),
                                                     conditionalPanel("input.PDL1_geneheatmap_samples_b4==true",
                                                                      selectizeInput(inputId= "PDL1_geneheatmap_samplelist_b4", label = "select your samples:",choices = PDL1_batch4_samples, multiple = TRUE)),
                                                     textAreaInput(inputId = "PDL1_geneheatmap_genelist_b4", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_dist_b4", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_hclust_b4", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_color_b4", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     sliderInput(inputId = "PDL1_geneheatmap_colsize_b4", label = "sample name size", min = 0, max = 20, value = 10, step = 1),
                                                     sliderInput(inputId = "PDL1_geneheatmap_rowsize_b4", label = "gene name size", min = 0, max = 20, value = 10, step = 1),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_geneheatmap_b4", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_hclust_heatmap_b4_out", height = "800px") %>% withSpinner(),
                                                 )
                                          ))),
                        tabPanel(title = tagList(icon("dna"), "batchAll"),
                                 fluidRow(column(width = 3,
                                                 box(title = tagList(icon("dna"), "Enter Parameters for the plot"),
                                                     width = NULL,
                                                     solidHeader = TRUE,
                                                     status = "primary",
                                                     footer = "press make plot to generate the new figure",
                                                     checkboxInput("PDL1_geneheatmap_samples_bAll","Select samples instead of showing all samples?", value=FALSE),
                                                     conditionalPanel("input.PDL1_geneheatmap_samples_bAll==true",
                                                                      selectizeInput(inputId= "PDL1_geneheatmap_samplelist_bAll", label = "select your samples:",choices = PDL1_all_samples, multiple = TRUE)),
                                                     textAreaInput(inputId = "PDL1_geneheatmap_genelist_bAll", label = "Enter your genes", rows = 5,
                                                                   value = "",
                                                                   placeholder = "Input one gene per line. At least 2 genes are required"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_dist_bAll", label = "distance method", choices = c("euclidean", "maximum", "manhattan", "canberra", "binary","minkowski"), selected = "euclidean"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_hclust_bAll", label = "hierarchical clustering method", choices =  c("ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"), selected = "complete"),
                                                     selectizeInput(inputId = "PDL1_geneheatmap_color_bAll", label = "color", choices =  c("RdYlGn", "GnBu", "cool_warm", "RdBu", "RdYlBu", "OrRd", "Spectral", "RdYlGn"), selected = "GnBu"),
                                                     sliderInput(inputId = "PDL1_geneheatmap_colsize_bAll", label = "sample name size", min = 0, max = 20, value = 5, step = 1),
                                                     sliderInput(inputId = "PDL1_geneheatmap_rowsize_bAll", label = "gene name size", min = 0, max = 20, value = 10, step = 1),
                                                     do.call(actionBttn, c(list( inputId = "PDL1_make_geneheatmap_bAll", label = "make plot", icon = icon("play")), actionBttnParams)),
                                                 )),
                                          column(width = 9,
                                                 box(title = "heatmap",
                                                     status = "primary",
                                                     solidHeader = TRUE,
                                                     width = NULL,
                                                     plotly::plotlyOutput("PDL1_hclust_heatmap_bAll_out", height = "800px") %>% withSpinner(),
                                                 )
                                          )))
                 )
)
)
